version: "3.9"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: sakila
      MYSQL_ROOT_PASSWORD: Hitema2025
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d  # <== montage du dossier contenant les dumps
    ports:
      - "3306:3306"


  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: sakila
      MYSQL_ROOT_PASSWORD: Hitema2025

volumes:
  mysql_data:
